networks:
  pyproject_starter-network:
    name: ${USER_NAME:-default}-pyproject_starter-network
secrets:
  package:
    file: secrets/package.txt
services:
  pyproject_starter_nginx:
    container_name: ${USER_NAME:-default}_pyproject_starter_nginx
    env_file: .env
    environment:
      PORT_NGINX: ${PORT_NGINX}
    image: nginx:alpine
    networks:
    - pyproject_starter-network
    ports:
    - ${PORT_NGINX}:80
    restart: always
    volumes:
    - ../docs/_build/html:/usr/share/nginx/html:ro
  pyproject_starter_python:
    build:
      context: ..
      dockerfile: docker/pytorch.Dockerfile
      shm_size: 1g
    cap_add:
    - SYS_PTRACE
    container_name: ${USER_NAME:-default}_pyproject_starter_python
    deploy:
      resources:
        reservations:
          devices:
          - capabilities:
            - gpu
    env_file: .env
    environment:
    - ENVIRONMENT=${ENVIRONMENT}
    - PORT_DASH=${PORT_DASH}
    - PORT_GOOGLE=${PORT_GOOGLE}
    - PORT_JUPYTER=${PORT_JUPYTER}
    - PORT_MLFLOW=${PORT_MLFLOW}
    - PORT_PROFILE=${PORT_PROFILE}
    - PORT_RAY_DASHBOARD=${PORT_RAY_DASHBOARD}
    - PORT_RAY_SERVER=${PORT_RAY_SERVER}
    image: pyproject_starter_python
    ipc: host
    networks:
    - pyproject_starter-network
    ports:
    - ${PORT_DASH}:${PORT_DASH}
    - ${PORT_GOOGLE}:${PORT_GOOGLE}
    - ${PORT_JUPYTER}:${PORT_JUPYTER}
    - ${PORT_MLFLOW}:5000
    - ${PORT_PROFILE}:${PORT_PROFILE}
    - ${PORT_RAY_DASHBOARD}:${PORT_RAY_DASHBOARD}
    - ${PORT_RAY_SERVER}:${PORT_RAY_SERVER}
    restart: always
    secrets:
    - package
    shm_size: 24g
    tty: true
    ulimits:
      memlock: -1
    volumes:
    - ..:/usr/src/pyproject_starter
    - ${DATA_DIR}:/usr/src/pyproject_starter/data
    - pyproject_starter-secret:/usr/src/pyproject_starter/docker/secrets
  pyproject_starter_streamlit:
    build:
      context: ..
      dockerfile: docker/streamlit.Dockerfile
    container_name: ${USER_NAME:-default}_pyproject_starter_streamlit
    env_file: .env
    environment:
      PORT_STREAMLIT: ${PORT_STREAMLIT}
    image: pyproject_starter_streamlit
    networks:
    - pyproject_starter-network
    ports:
    - $PORT_STREAMLIT:8501
    restart: always
    volumes:
    - ../applications/streamlit:/usr/src/pyproject_starter/applications/streamlit
volumes:
  pyproject_starter-secret: null
